import Provider from '@/components/provider';
import { cn } from '@/lib/utils';
import '@/styles/tailwind.css';
import type { Metadata } from 'next';
import localFont from 'next/font/local';

export const metadata: Metadata = {
  title: 'Next.js enterprise ready',
  description: 'Generated by Hi next app',
};
export async function generateStaticParams() {
  return [{ lang: 'en-US' }, { lang: 'mm' }];
}
const Angoun = localFont({
  src: './fonts/MyanmarAngoun.ttf',
  display: 'swap',
  variable: '--myanmar-angoun-font',
});

export default function RootLayout({
  children,
  params: { lang },
}: Readonly<{
  children: React.ReactNode;
  params: { lang: string };
}>) {
  return (
    <html lang={lang} suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={cn(
          'bg-white transition-colors duration-200 dark:bg-black',
          Angoun.className,
        )}
      >
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
